# Generated by Django 5.2.14 on 2026-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
