# Generated by Django 5.2.14 on 2026-06-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
